In [11]:
import torch
from moco.loader import TwoCropsTransform
from moco.builder import MoCo
import torchvision.models as models
import torchvision.datasets as datasets
import os
import torchvision.transforms as transforms

In [2]:
model = MoCo(
        models.__dict__["resnet50"],
        4096,
        128,
        0.07,
        False,
    )

In [3]:
statedict = torch.load("/mnt/nvme0n1p2/Moco-MAC/SOCOLA/checkpoint_0026.pth.tar")
model.load_state_dict(statedict["state_dict"])
img_encoder = model.encoder_img

dict_keys(['epoch', 'arch', 'state_dict', 'optimizer'])

In [9]:
datadir = "/mnt/nvme0n1p2/CVPR"
normalize = transforms.Normalize(
        mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
    )
augmentation = [
            transforms.RandomResizedCrop(224, scale=(0.2, 1.0)),
            transforms.RandomGrayscale(p=0.2),
            transforms.ColorJitter(0.4, 0.4, 0.4, 0.4),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            normalize,
        ]
transform = transforms.Compose(augmentation)

In [25]:
from PIL import Image

image = Image.open("/mnt/nvme0n1p2/CVPR/ILSVRC/imagenet/n01443537/n01443537_2.JPEG")
image2 = Image.open("/mnt/nvme0n1p2/CVPR/ILSVRC/imagenet/n01514668/n01514668_19.JPEG")

In [26]:

input_tensor = transform(image).unsqueeze(0) 
input_tensor2 = transform(image2).unsqueeze(0)

In [27]:
with torch.no_grad():
    output = img_encoder(input_tensor)
    output2 = img_encoder(input_tensor2)
output.shape

torch.Size([1, 128])

In [28]:
output, output2

(tensor([[ 459.9450,  -76.3719,   20.2474, -169.8112,  165.9793, -170.7895,
           -11.2320,   10.9582, -137.7367,  109.3520,  101.3494, -199.4001,
           179.7178,  525.8248, -166.8260,    2.0205,  254.0179,   75.0359,
          -190.1045, -246.1027, -320.7498, -140.6209,  104.3099,  -78.6841,
           269.8926,  360.7146,  258.0661,  420.9211, -394.2073,  -36.1153,
          -165.9484, -128.2647, -142.6000,  106.1852,   48.6809, -347.4110,
          -180.2103, -247.4691, -295.6267,  -52.8179,   53.4990,  186.6651,
          -145.7894,   89.4216,  -90.5319,  126.9309,   15.9375,  177.5821,
           171.5459,  -48.0388,   35.8931,  290.6874,   22.2475,   43.0691,
           390.5434,  422.7316,  268.3035, -126.6159,  214.3989,   86.8073,
           216.4792, -107.2984,  -99.9883,   75.1593,   61.1626, -246.4920,
          -479.2994, -116.0367,  231.7850,   40.3719,  138.8003, -438.2425,
          -217.2004,  387.8965,  287.4699, -131.3202,  227.6157, -165.1593,
            

In [29]:
import torch.nn.functional as F
output = F.normalize(output, dim=1)
output2 = F.normalize(output2, dim=1)
output, output2

(tensor([[ 0.1807, -0.0300,  0.0080, -0.0667,  0.0652, -0.0671, -0.0044,  0.0043,
          -0.0541,  0.0430,  0.0398, -0.0783,  0.0706,  0.2066, -0.0655,  0.0008,
           0.0998,  0.0295, -0.0747, -0.0967, -0.1260, -0.0552,  0.0410, -0.0309,
           0.1060,  0.1417,  0.1014,  0.1654, -0.1549, -0.0142, -0.0652, -0.0504,
          -0.0560,  0.0417,  0.0191, -0.1365, -0.0708, -0.0972, -0.1161, -0.0208,
           0.0210,  0.0733, -0.0573,  0.0351, -0.0356,  0.0499,  0.0063,  0.0698,
           0.0674, -0.0189,  0.0141,  0.1142,  0.0087,  0.0169,  0.1534,  0.1661,
           0.1054, -0.0497,  0.0842,  0.0341,  0.0851, -0.0422, -0.0393,  0.0295,
           0.0240, -0.0968, -0.1883, -0.0456,  0.0911,  0.0159,  0.0545, -0.1722,
          -0.0853,  0.1524,  0.1129, -0.0516,  0.0894, -0.0649,  0.0326,  0.0122,
          -0.0515,  0.0132,  0.1328, -0.1827,  0.1479, -0.0618, -0.0112, -0.0756,
           0.0103, -0.0617, -0.0127, -0.0492,  0.1817, -0.0490,  0.0146,  0.0505,
           0.010

In [30]:
output @ output2.T

tensor([[1.]])